const js = require("@eslint/js");

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "commonjs",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        exports: "writable",
        module: "writable",
        require: "readonly",
        global: "readonly",
        // Test globals (Jest and Mocha)
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        jest: "readonly",
        // Mocha globals
        suite: "readonly",
        suiteSetup: "readonly",
        suiteTeardown: "readonly",
        setup: "readonly",
        teardown: "readonly",
      },
    },
    rules: {
      indent: ["error", 2],
      semi: ["error", "always"],
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      "no-trailing-spaces": "error",
      "eol-last": "error",
      "comma-dangle": ["error", "only-multiline"],
      "object-curly-spacing": ["error", "always"],
      "array-bracket-spacing": ["error", "never"],
      "space-before-blocks": "error",
      "keyword-spacing": "error",
      "space-infix-ops": "error",
      "no-multiple-empty-lines": ["error", { max: 1, maxEOF: 1 }],
      "consistent-return": "error",
      "no-var": "error",
      "prefer-const": "error",
      "prefer-arrow-callback": "error",
    },
  },
  {
    files: ["**/*.test.js"],
    rules: {
      "no-console": "off",
      "prefer-arrow-callback": "off",
      "func-names": "off",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "consistent-return": "off",
    },
  },
];
